version: "3.9"

services:
  python-app:
    image: llama-3B-SAE-tinystories
    build:
      context: .
    secrets:
      - hf_token
      - wandb_token
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: ["gpu"]

secrets:
  hf_token:
    external: true
  wandb_token:
    external: true